steps:
  - name: ":golang: tests"
    command: .buildkite/test.sh
  - name: ":golang: compile binaries"
    command: .buildkite/build.sh
  - wait
  - name: ":github: :docker: :aws: release! :allthethings:"
    command: .buildkite/release.sh
  - wait
  - name: ":ec2: kubernetes deploy"
    command: .buildkite/deploy.sh
    branches: v*.*
    agents:
      queue: deploy
      kubernetes: true
